# Generated by carnix 0.7.2: ../carnix/target/debug/carnix build
{ pkgs ? import <nixpkgs> {}}: with pkgs;

let kernel = buildPlatform.parsed.kernel.name;
    abi = buildPlatform.parsed.abi.name;
    include = includedFiles: src: builtins.filterSource (path: type:
      lib.lists.any (f:
        let p = toString (src + ("/" + f)); in
        (path == p) || (type == "directory" && lib.strings.hasPrefix path p)
      ) includedFiles
    ) src;
    updateFeatures = f: up: functions: builtins.deepSeq f (lib.lists.foldl' (features: fun: fun features) (lib.attrsets.recursiveUpdate f up) functions);
    mapFeatures = features: map (fun: fun { features = features; });
    mkFeatures = feat: lib.lists.foldl (features: featureName:
      if feat.${featureName} or false then
        [ featureName ] ++ features
      else
        features
    ) [] (builtins.attrNames feat);
in
rec {
  nixdoc = f: nixdoc_1_0_1 { features = nixdoc_1_0_1_features { nixdoc_1_0_1 = f; }; };
  __all = [ (nixdoc {}) ];
  ansi_term_0_11_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "ansi_term";
    version = "0.11.0";
    authors = [ "ogham@bsago.me" "Ryan Scheel (Havvy) <ryan.havvy@gmail.com>" "Josh Triplett <josh@joshtriplett.org>" ];
    sha256 = "08fk0p2xvkqpmz3zlrwnf6l8sj2vngw464rvzspzp31sbgxbwm4v";
    inherit dependencies buildDependencies features;
  };
  atty_0_2_11_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "atty";
    version = "0.2.11";
    authors = [ "softprops <d.tangren@gmail.com>" ];
    sha256 = "0by1bj2km9jxi4i4g76zzi76fc2rcm9934jpnyrqd95zw344pb20";
    inherit dependencies buildDependencies features;
  };
  backtrace_0_3_9_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "backtrace";
    version = "0.3.9";
    authors = [ "Alex Crichton <alex@alexcrichton.com>" "The Rust Project Developers" ];
    sha256 = "137pjkcn89b7fqk78w65ggj92pynmf1hkr1sjz53aga4b50lkmwm";
    inherit dependencies buildDependencies features;
  };
  backtrace_sys_0_1_24_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "backtrace-sys";
    version = "0.1.24";
    authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
    sha256 = "15d6jlknykiijcin3vqbx33760w24ss5qw3l1xd3hms5k4vc8305";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  bitflags_1_0_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "bitflags";
    version = "1.0.4";
    authors = [ "The Rust Project Developers" ];
    sha256 = "1g1wmz2001qmfrd37dnd5qiss5njrw26aywmg6yhkmkbyrhjxb08";
    inherit dependencies buildDependencies features;
  };
  cc_1_0_25_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "cc";
    version = "1.0.25";
    authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
    sha256 = "0pd8fhjlpr5qan984frkf1c8nxrqp6827wmmfzhm2840229z2hq0";
    inherit dependencies buildDependencies features;
  };
  cfg_if_0_1_6_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "cfg-if";
    version = "0.1.6";
    authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
    sha256 = "11qrix06wagkplyk908i3423ps9m9np6c4vbcq81s9fyl244xv3n";
    inherit dependencies buildDependencies features;
  };
  clap_2_32_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "clap";
    version = "2.32.0";
    authors = [ "Kevin K. <kbknapp@gmail.com>" ];
    sha256 = "1hdjf0janvpjkwrjdjx1mm2aayzr54k72w6mriyr0n5anjkcj1lx";
    inherit dependencies buildDependencies features;
  };
  cloudabi_0_0_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "cloudabi";
    version = "0.0.3";
    authors = [ "Nuxi (https://nuxi.nl/) and contributors" ];
    sha256 = "1z9lby5sr6vslfd14d6igk03s7awf91mxpsfmsp3prxbxlk0x7h5";
    libPath = "cloudabi.rs";
    inherit dependencies buildDependencies features;
  };
  failure_0_1_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "failure";
    version = "0.1.3";
    authors = [ "Without Boats <boats@mozilla.com>" ];
    sha256 = "0cibp01z0clyxrvkl7v7kq6jszsgcg9vwv6d9l6d1drk9jqdss4s";
    inherit dependencies buildDependencies features;
  };
  failure_derive_0_1_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "failure_derive";
    version = "0.1.3";
    authors = [ "Without Boats <woboats@gmail.com>" ];
    sha256 = "1mh7ad2d17f13g0k29bskp0f9faws0w1q4a5yfzlzi75bw9kidgm";
    procMacro = true;
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  fuchsia_zircon_0_3_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "fuchsia-zircon";
    version = "0.3.3";
    authors = [ "Raph Levien <raph@google.com>" ];
    sha256 = "0jrf4shb1699r4la8z358vri8318w4mdi6qzfqy30p2ymjlca4gk";
    inherit dependencies buildDependencies features;
  };
  fuchsia_zircon_sys_0_3_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "fuchsia-zircon-sys";
    version = "0.3.3";
    authors = [ "Raph Levien <raph@google.com>" ];
    sha256 = "08jp1zxrm9jbrr6l26bjal4dbm8bxfy57ickdgibsqxr1n9j3hf5";
    inherit dependencies buildDependencies features;
  };
  heck_0_3_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "heck";
    version = "0.3.0";
    authors = [ "Without Boats <woboats@gmail.com>" ];
    sha256 = "1cg062awkhr82ymwd1qyf0rz289gqhix82j94x1xr2g6w30pady1";
    inherit dependencies buildDependencies features;
  };
  libc_0_2_43_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "libc";
    version = "0.2.43";
    authors = [ "The Rust Project Developers" ];
    sha256 = "0pshydmsq71kl9276zc2928ld50sp524ixcqkcqsgq410dx6c50b";
    inherit dependencies buildDependencies features;
  };
  lock_api_0_1_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "lock_api";
    version = "0.1.4";
    authors = [ "Amanieu d'Antras <amanieu@gmail.com>" ];
    sha256 = "055dl3crjiid0bsmrwp3z3s6ypgscv4zsqgdj0pmhxr6zaas1da2";
    inherit dependencies buildDependencies features;
  };
  nixdoc_1_0_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "nixdoc";
    version = "1.0.1";
    authors = [ "Vincent Ambo <mail@tazj.in>" ];
    src = ./.;
    inherit dependencies buildDependencies features;
  };
  owning_ref_0_3_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "owning_ref";
    version = "0.3.3";
    authors = [ "Marvin Löbel <loebel.marvin@gmail.com>" ];
    sha256 = "13ivn0ydc0hf957ix0f5si9nnplzzykbr70hni1qz9m19i9kvmrh";
    inherit dependencies buildDependencies features;
  };
  parking_lot_0_6_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "parking_lot";
    version = "0.6.4";
    authors = [ "Amanieu d'Antras <amanieu@gmail.com>" ];
    sha256 = "0qwfysx8zfkj72sfcrqvd6pp7lgjmklyixsi3y0g6xjspw876rax";
    inherit dependencies buildDependencies features;
  };
  parking_lot_core_0_3_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "parking_lot_core";
    version = "0.3.1";
    authors = [ "Amanieu d'Antras <amanieu@gmail.com>" ];
    sha256 = "0h5p7dys8cx9y6ii4i57ampf7qdr8zmkpn543kd3h7nkhml8bw72";
    inherit dependencies buildDependencies features;
  };
  proc_macro2_0_4_20_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "proc-macro2";
    version = "0.4.20";
    authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
    sha256 = "0yr74b00d3wzg21kjvfln7vzzvf9aghbaff4c747i3grbd997ys2";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  quote_0_6_9_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "quote";
    version = "0.6.9";
    authors = [ "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "06fd7a81nmiphpj0lfz1hys7j0b9c3hnnnw7ycv8l88l8b70mkgl";
    inherit dependencies buildDependencies features;
  };
  rand_0_5_5_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "rand";
    version = "0.5.5";
    authors = [ "The Rust Project Developers" ];
    sha256 = "0d7pnsh57qxhz1ghrzk113ddkn13kf2g758ffnbxq4nhwjfzhlc9";
    inherit dependencies buildDependencies features;
  };
  rand_core_0_2_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "rand_core";
    version = "0.2.2";
    authors = [ "The Rust Project Developers" ];
    sha256 = "1cxnaxmsirz2wxsajsjkd1wk6lqfqbcprqkha4bq3didznrl22sc";
    inherit dependencies buildDependencies features;
  };
  rand_core_0_3_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "rand_core";
    version = "0.3.0";
    authors = [ "The Rust Project Developers" ];
    sha256 = "1vafw316apjys9va3j987s02djhqp7y21v671v3ix0p5j9bjq339";
    inherit dependencies buildDependencies features;
  };
  redox_syscall_0_1_40_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "redox_syscall";
    version = "0.1.40";
    authors = [ "Jeremy Soller <jackpot51@gmail.com>" ];
    sha256 = "132rnhrq49l3z7gjrwj2zfadgw6q0355s6a7id7x7c0d7sk72611";
    libName = "syscall";
    inherit dependencies buildDependencies features;
  };
  redox_termios_0_1_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "redox_termios";
    version = "0.1.1";
    authors = [ "Jeremy Soller <jackpot51@gmail.com>" ];
    sha256 = "04s6yyzjca552hdaqlvqhp3vw0zqbc304md5czyd3axh56iry8wh";
    libPath = "src/lib.rs";
    inherit dependencies buildDependencies features;
  };
  rnix_0_5_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "rnix";
    version = "0.5.0";
    authors = [ "jD91mZM2 <me@krake.one>" ];
    src = fetchgit {
       url = "https://gitlab.com/jD91mZM2/rnix.git";
       rev = "d76b57b6a7d667c34bea5ed212539f9ac6af9c77";
       sha256 = "1b0i4i6if5w1plkl9psgkcqik9cgz7f14qaddcafbsrrxg80sxz0";
       fetchSubmodules = false;
    };
    inherit dependencies buildDependencies features;
  };
  rowan_0_1_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "rowan";
    version = "0.1.2";
    authors = [ "Aleksey Kladov <aleksey.kladov@gmail.com>" ];
    src = fetchgit {
       url = "https://github.com/matklad/rowan.git";
       rev = "058042cfbed9f20e35ae7adb23b7945b37bbffed";
       sha256 = "190bz8yvhw2awc026zf7qww7i55ryvyp3y7zzrl3x451wg898hdl";
       fetchSubmodules = false;
    };
    inherit dependencies buildDependencies features;
  };
  rustc_demangle_0_1_9_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "rustc-demangle";
    version = "0.1.9";
    authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
    sha256 = "00ma4r9haq0zv5krps617mym6y74056pfcivyld0kpci156vfaax";
    inherit dependencies buildDependencies features;
  };
  rustc_version_0_2_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "rustc_version";
    version = "0.2.3";
    authors = [ "Marvin Löbel <loebel.marvin@gmail.com>" ];
    sha256 = "0rgwzbgs3i9fqjm1p4ra3n7frafmpwl29c8lw85kv1rxn7n2zaa7";
    inherit dependencies buildDependencies features;
  };
  scopeguard_0_3_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "scopeguard";
    version = "0.3.3";
    authors = [ "bluss" ];
    sha256 = "0i1l013csrqzfz6c68pr5pi01hg5v5yahq8fsdmaxy6p8ygsjf3r";
    inherit dependencies buildDependencies features;
  };
  semver_0_9_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "semver";
    version = "0.9.0";
    authors = [ "Steve Klabnik <steve@steveklabnik.com>" "The Rust Project Developers" ];
    sha256 = "0azak2lb2wc36s3x15az886kck7rpnksrw14lalm157rg9sc9z63";
    inherit dependencies buildDependencies features;
  };
  semver_parser_0_7_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "semver-parser";
    version = "0.7.0";
    authors = [ "Steve Klabnik <steve@steveklabnik.com>" ];
    sha256 = "1da66c8413yakx0y15k8c055yna5lyb6fr0fw9318kdwkrk5k12h";
    inherit dependencies buildDependencies features;
  };
  smallvec_0_6_5_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "smallvec";
    version = "0.6.5";
    authors = [ "Simon Sapin <simon.sapin@exyr.org>" ];
    sha256 = "0jx49nb1c91936jaq30axc96wncdp2wdmspf1qc8iv85f1i44vvf";
    libPath = "lib.rs";
    inherit dependencies buildDependencies features;
  };
  smol_str_0_1_7_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "smol_str";
    version = "0.1.7";
    authors = [ "Aleksey Kladov <aleksey.kladov@gmail.com>" ];
    sha256 = "1h9bixysjk805ayfqddwfxqbqchfyiji6g0ylrz27j4j9ip6ky7n";
    inherit dependencies buildDependencies features;
  };
  stable_deref_trait_1_1_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "stable_deref_trait";
    version = "1.1.1";
    authors = [ "Robert Grosse <n210241048576@gmail.com>" ];
    sha256 = "1xy9slzslrzr31nlnw52sl1d820b09y61b7f13lqgsn8n7y0l4g8";
    inherit dependencies buildDependencies features;
  };
  strsim_0_7_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "strsim";
    version = "0.7.0";
    authors = [ "Danny Guo <dannyguo91@gmail.com>" ];
    sha256 = "0fy0k5f2705z73mb3x9459bpcvrx4ky8jpr4zikcbiwan4bnm0iv";
    inherit dependencies buildDependencies features;
  };
  structopt_0_2_13_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "structopt";
    version = "0.2.13";
    authors = [ "Guillaume Pinot <texitoi@texitoi.eu>" "others" ];
    sha256 = "0jaf9n8z68hf1hyan59jd0wx7jpf1wi4gdkmpigsckwq9ypw8nvz";
    inherit dependencies buildDependencies features;
  };
  structopt_derive_0_2_13_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "structopt-derive";
    version = "0.2.13";
    authors = [ "Guillaume Pinot <texitoi@texitoi.eu>" ];
    sha256 = "1fhc69rni0znpb9s6lfgd292xfqifkxwfknd8mgjpd195cs82ndg";
    procMacro = true;
    inherit dependencies buildDependencies features;
  };
  syn_0_15_18_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "syn";
    version = "0.15.18";
    authors = [ "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "1ckcw83932gqagz246934fs78gj5mw7qf5dm1bkwp6chj0gx1vgh";
    inherit dependencies buildDependencies features;
  };
  synstructure_0_10_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "synstructure";
    version = "0.10.1";
    authors = [ "Nika Layzell <nika@thelayzells.com>" ];
    sha256 = "0mx2vwd0d0f7hanz15nkp0ikkfjsx9rfkph7pynxyfbj45ank4g3";
    inherit dependencies buildDependencies features;
  };
  termion_1_5_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "termion";
    version = "1.5.1";
    authors = [ "ticki <Ticki@users.noreply.github.com>" "gycos <alexandre.bury@gmail.com>" "IGI-111 <igi-111@protonmail.com>" ];
    sha256 = "02gq4vd8iws1f3gjrgrgpajsk2bk43nds5acbbb4s8dvrdvr8nf1";
    inherit dependencies buildDependencies features;
  };
  text_unit_0_1_5_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "text_unit";
    version = "0.1.5";
    authors = [ "Aleksey Kladov <aleksey.kladov@gmail.com>" ];
    sha256 = "1df8avj873plw0syayfh01xkr1aj90bsxb64wpjh14732znn0v2w";
    inherit dependencies buildDependencies features;
  };
  textwrap_0_10_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "textwrap";
    version = "0.10.0";
    authors = [ "Martin Geisler <martin@geisler.net>" ];
    sha256 = "1s8d5cna12smhgj0x2y1xphklyk2an1yzbadnj89p1vy5vnjpsas";
    inherit dependencies buildDependencies features;
  };
  unicode_segmentation_1_2_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "unicode-segmentation";
    version = "1.2.1";
    authors = [ "kwantam <kwantam@gmail.com>" ];
    sha256 = "0pzydlrq019cdiqbbfq205cskxcspwi97zfdi02rma21br1kc59m";
    inherit dependencies buildDependencies features;
  };
  unicode_width_0_1_5_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "unicode-width";
    version = "0.1.5";
    authors = [ "kwantam <kwantam@gmail.com>" ];
    sha256 = "0886lc2aymwgy0lhavwn6s48ik3c61ykzzd3za6prgnw51j7bi4w";
    inherit dependencies buildDependencies features;
  };
  unicode_xid_0_1_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "unicode-xid";
    version = "0.1.0";
    authors = [ "erick.tryzelaar <erick.tryzelaar@gmail.com>" "kwantam <kwantam@gmail.com>" ];
    sha256 = "05wdmwlfzxhq3nhsxn6wx4q8dhxzzfb9szsz6wiw092m1rjj01zj";
    inherit dependencies buildDependencies features;
  };
  unreachable_1_0_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "unreachable";
    version = "1.0.0";
    authors = [ "Jonathan Reem <jonathan.reem@gmail.com>" ];
    sha256 = "1am8czbk5wwr25gbp2zr007744fxjshhdqjz9liz7wl4pnv3whcf";
    inherit dependencies buildDependencies features;
  };
  vec_map_0_8_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "vec_map";
    version = "0.8.1";
    authors = [ "Alex Crichton <alex@alexcrichton.com>" "Jorge Aparicio <japaricious@gmail.com>" "Alexis Beingessner <a.beingessner@gmail.com>" "Brian Anderson <>" "tbu- <>" "Manish Goregaokar <>" "Aaron Turon <aturon@mozilla.com>" "Adolfo Ochagavía <>" "Niko Matsakis <>" "Steven Fackler <>" "Chase Southwood <csouth3@illinois.edu>" "Eduard Burtescu <>" "Florian Wilkens <>" "Félix Raimundo <>" "Tibor Benke <>" "Markus Siemens <markus@m-siemens.de>" "Josh Branchaud <jbranchaud@gmail.com>" "Huon Wilson <dbau.pp@gmail.com>" "Corey Farwell <coref@rwell.org>" "Aaron Liblong <>" "Nick Cameron <nrc@ncameron.org>" "Patrick Walton <pcwalton@mimiga.net>" "Felix S Klock II <>" "Andrew Paseltiner <apaseltiner@gmail.com>" "Sean McArthur <sean.monstar@gmail.com>" "Vadim Petrochenkov <>" ];
    sha256 = "1jj2nrg8h3l53d43rwkpkikq5a5x15ms4rf1rw92hp5lrqhi8mpi";
    inherit dependencies buildDependencies features;
  };
  void_1_0_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "void";
    version = "1.0.2";
    authors = [ "Jonathan Reem <jonathan.reem@gmail.com>" ];
    sha256 = "0h1dm0dx8dhf56a83k68mijyxigqhizpskwxfdrs1drwv2cdclv3";
    inherit dependencies buildDependencies features;
  };
  winapi_0_3_6_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "winapi";
    version = "0.3.6";
    authors = [ "Peter Atashian <retep998@gmail.com>" ];
    sha256 = "1d9jfp4cjd82sr1q4dgdlrkvm33zhhav9d7ihr0nivqbncr059m4";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  winapi_i686_pc_windows_gnu_0_4_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "winapi-i686-pc-windows-gnu";
    version = "0.4.0";
    authors = [ "Peter Atashian <retep998@gmail.com>" ];
    sha256 = "05ihkij18r4gamjpxj4gra24514can762imjzlmak5wlzidplzrp";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  winapi_x86_64_pc_windows_gnu_0_4_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "winapi-x86_64-pc-windows-gnu";
    version = "0.4.0";
    authors = [ "Peter Atashian <retep998@gmail.com>" ];
    sha256 = "0n1ylmlsb8yg1v583i4xy0qmqg42275flvbc51hdqjjfjcl9vlbj";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  xml_rs_0_8_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "xml-rs";
    version = "0.8.0";
    authors = [ "Vladimir Matveev <vladimir.matweev@gmail.com>" ];
    sha256 = "1l3g4wmbz611jwx2a1ni4jyj0ffnls3s7a7rbdn6c763k85k7zs5";
    libPath = "src/lib.rs";
    libName = "xml";
    crateBin = [ {  name = "xml-analyze";  path = "src/analyze.rs"; } ];
    inherit dependencies buildDependencies features;
  };
  ansi_term_0_11_0 = { features?(ansi_term_0_11_0_features {}) }: ansi_term_0_11_0_ {
    dependencies = (if kernel == "windows" then mapFeatures features ([ winapi_0_3_6 ]) else []);
  };
  ansi_term_0_11_0_features = f: updateFeatures f (rec {
    ansi_term_0_11_0.default = (f.ansi_term_0_11_0.default or true);
    winapi_0_3_6.consoleapi = true;
    winapi_0_3_6.default = true;
    winapi_0_3_6.errhandlingapi = true;
    winapi_0_3_6.processenv = true;
  }) [ winapi_0_3_6_features ];
  atty_0_2_11 = { features?(atty_0_2_11_features {}) }: atty_0_2_11_ {
    dependencies = (if kernel == "redox" then mapFeatures features ([ termion_1_5_1 ]) else [])
      ++ (if (kernel == "linux" || kernel == "darwin") then mapFeatures features ([ libc_0_2_43 ]) else [])
      ++ (if kernel == "windows" then mapFeatures features ([ winapi_0_3_6 ]) else []);
  };
  atty_0_2_11_features = f: updateFeatures f (rec {
    atty_0_2_11.default = (f.atty_0_2_11.default or true);
    libc_0_2_43.default = (f.libc_0_2_43.default or false);
    termion_1_5_1.default = true;
    winapi_0_3_6.consoleapi = true;
    winapi_0_3_6.default = true;
    winapi_0_3_6.minwinbase = true;
    winapi_0_3_6.minwindef = true;
    winapi_0_3_6.processenv = true;
    winapi_0_3_6.winbase = true;
  }) [ termion_1_5_1_features libc_0_2_43_features winapi_0_3_6_features ];
  backtrace_0_3_9 = { features?(backtrace_0_3_9_features {}) }: backtrace_0_3_9_ {
    dependencies = mapFeatures features ([ cfg_if_0_1_6 rustc_demangle_0_1_9 ])
      ++ (if (kernel == "linux" || kernel == "darwin") && !(kernel == "fuchsia") && !(kernel == "emscripten") && !(kernel == "darwin") && !(kernel == "ios") then mapFeatures features ([ ]
      ++ (if features.backtrace_0_3_9."backtrace-sys" or false then [ backtrace_sys_0_1_24 ] else [])) else [])
      ++ (if (kernel == "linux" || kernel == "darwin") then mapFeatures features ([ libc_0_2_43 ]) else [])
      ++ (if kernel == "windows" then mapFeatures features ([ ]
      ++ (if features.backtrace_0_3_9.winapi or false then [ winapi_0_3_6 ] else [])) else []);
    features = mkFeatures (features.backtrace_0_3_9 or {});
  };
  backtrace_0_3_9_features = f: updateFeatures f (rec {
    backtrace_0_3_9."addr2line" =
      (f.backtrace_0_3_9."addr2line" or false) ||
      (f.backtrace_0_3_9."gimli-symbolize" or false) ||
      (backtrace_0_3_9."gimli-symbolize" or false);
    backtrace_0_3_9."backtrace-sys" =
      (f.backtrace_0_3_9."backtrace-sys" or false) ||
      (f.backtrace_0_3_9.libbacktrace or false) ||
      (backtrace_0_3_9.libbacktrace or false);
    backtrace_0_3_9."rustc-serialize" =
      (f.backtrace_0_3_9."rustc-serialize" or false) ||
      (f.backtrace_0_3_9."serialize-rustc" or false) ||
      (backtrace_0_3_9."serialize-rustc" or false);
    backtrace_0_3_9.coresymbolication =
      (f.backtrace_0_3_9.coresymbolication or false) ||
      (f.backtrace_0_3_9.default or false) ||
      (backtrace_0_3_9.default or false);
    backtrace_0_3_9.dbghelp =
      (f.backtrace_0_3_9.dbghelp or false) ||
      (f.backtrace_0_3_9.default or false) ||
      (backtrace_0_3_9.default or false);
    backtrace_0_3_9.default = (f.backtrace_0_3_9.default or true);
    backtrace_0_3_9.dladdr =
      (f.backtrace_0_3_9.dladdr or false) ||
      (f.backtrace_0_3_9.default or false) ||
      (backtrace_0_3_9.default or false);
    backtrace_0_3_9.findshlibs =
      (f.backtrace_0_3_9.findshlibs or false) ||
      (f.backtrace_0_3_9."gimli-symbolize" or false) ||
      (backtrace_0_3_9."gimli-symbolize" or false);
    backtrace_0_3_9.gimli =
      (f.backtrace_0_3_9.gimli or false) ||
      (f.backtrace_0_3_9."gimli-symbolize" or false) ||
      (backtrace_0_3_9."gimli-symbolize" or false);
    backtrace_0_3_9.libbacktrace =
      (f.backtrace_0_3_9.libbacktrace or false) ||
      (f.backtrace_0_3_9.default or false) ||
      (backtrace_0_3_9.default or false);
    backtrace_0_3_9.libunwind =
      (f.backtrace_0_3_9.libunwind or false) ||
      (f.backtrace_0_3_9.default or false) ||
      (backtrace_0_3_9.default or false);
    backtrace_0_3_9.memmap =
      (f.backtrace_0_3_9.memmap or false) ||
      (f.backtrace_0_3_9."gimli-symbolize" or false) ||
      (backtrace_0_3_9."gimli-symbolize" or false);
    backtrace_0_3_9.object =
      (f.backtrace_0_3_9.object or false) ||
      (f.backtrace_0_3_9."gimli-symbolize" or false) ||
      (backtrace_0_3_9."gimli-symbolize" or false);
    backtrace_0_3_9.serde =
      (f.backtrace_0_3_9.serde or false) ||
      (f.backtrace_0_3_9."serialize-serde" or false) ||
      (backtrace_0_3_9."serialize-serde" or false);
    backtrace_0_3_9.serde_derive =
      (f.backtrace_0_3_9.serde_derive or false) ||
      (f.backtrace_0_3_9."serialize-serde" or false) ||
      (backtrace_0_3_9."serialize-serde" or false);
    backtrace_0_3_9.winapi =
      (f.backtrace_0_3_9.winapi or false) ||
      (f.backtrace_0_3_9.dbghelp or false) ||
      (backtrace_0_3_9.dbghelp or false);
    backtrace_sys_0_1_24.default = true;
    cfg_if_0_1_6.default = true;
    libc_0_2_43.default = true;
    rustc_demangle_0_1_9.default = true;
    winapi_0_3_6.dbghelp = true;
    winapi_0_3_6.default = true;
    winapi_0_3_6.minwindef = true;
    winapi_0_3_6.processthreadsapi = true;
    winapi_0_3_6.std = true;
    winapi_0_3_6.winnt = true;
  }) [ cfg_if_0_1_6_features rustc_demangle_0_1_9_features backtrace_sys_0_1_24_features libc_0_2_43_features winapi_0_3_6_features ];
  backtrace_sys_0_1_24 = { features?(backtrace_sys_0_1_24_features {}) }: backtrace_sys_0_1_24_ {
    dependencies = mapFeatures features ([ libc_0_2_43 ]);
    buildDependencies = mapFeatures features ([ cc_1_0_25 ]);
  };
  backtrace_sys_0_1_24_features = f: updateFeatures f (rec {
    backtrace_sys_0_1_24.default = (f.backtrace_sys_0_1_24.default or true);
    cc_1_0_25.default = true;
    libc_0_2_43.default = true;
  }) [ libc_0_2_43_features cc_1_0_25_features ];
  bitflags_1_0_4 = { features?(bitflags_1_0_4_features {}) }: bitflags_1_0_4_ {
    features = mkFeatures (features.bitflags_1_0_4 or {});
  };
  bitflags_1_0_4_features = f: updateFeatures f (rec {
    bitflags_1_0_4.default = (f.bitflags_1_0_4.default or true);
  }) [];
  cc_1_0_25 = { features?(cc_1_0_25_features {}) }: cc_1_0_25_ {
    dependencies = mapFeatures features ([]);
    features = mkFeatures (features.cc_1_0_25 or {});
  };
  cc_1_0_25_features = f: updateFeatures f (rec {
    cc_1_0_25.default = (f.cc_1_0_25.default or true);
    cc_1_0_25.rayon =
      (f.cc_1_0_25.rayon or false) ||
      (f.cc_1_0_25.parallel or false) ||
      (cc_1_0_25.parallel or false);
  }) [];
  cfg_if_0_1_6 = { features?(cfg_if_0_1_6_features {}) }: cfg_if_0_1_6_ {};
  cfg_if_0_1_6_features = f: updateFeatures f (rec {
    cfg_if_0_1_6.default = (f.cfg_if_0_1_6.default or true);
  }) [];
  clap_2_32_0 = { features?(clap_2_32_0_features {}) }: clap_2_32_0_ {
    dependencies = mapFeatures features ([ bitflags_1_0_4 textwrap_0_10_0 unicode_width_0_1_5 ]
      ++ (if features.clap_2_32_0.atty or false then [ atty_0_2_11 ] else [])
      ++ (if features.clap_2_32_0.strsim or false then [ strsim_0_7_0 ] else [])
      ++ (if features.clap_2_32_0.vec_map or false then [ vec_map_0_8_1 ] else []))
      ++ (if !(kernel == "windows") then mapFeatures features ([ ]
      ++ (if features.clap_2_32_0.ansi_term or false then [ ansi_term_0_11_0 ] else [])) else []);
    features = mkFeatures (features.clap_2_32_0 or {});
  };
  clap_2_32_0_features = f: updateFeatures f (rec {
    ansi_term_0_11_0.default = true;
    atty_0_2_11.default = true;
    bitflags_1_0_4.default = true;
    clap_2_32_0."yaml-rust" =
      (f.clap_2_32_0."yaml-rust" or false) ||
      (f.clap_2_32_0.yaml or false) ||
      (clap_2_32_0.yaml or false);
    clap_2_32_0.ansi_term =
      (f.clap_2_32_0.ansi_term or false) ||
      (f.clap_2_32_0.color or false) ||
      (clap_2_32_0.color or false);
    clap_2_32_0.atty =
      (f.clap_2_32_0.atty or false) ||
      (f.clap_2_32_0.color or false) ||
      (clap_2_32_0.color or false);
    clap_2_32_0.clippy =
      (f.clap_2_32_0.clippy or false) ||
      (f.clap_2_32_0.lints or false) ||
      (clap_2_32_0.lints or false);
    clap_2_32_0.color =
      (f.clap_2_32_0.color or false) ||
      (f.clap_2_32_0.default or false) ||
      (clap_2_32_0.default or false);
    clap_2_32_0.default = (f.clap_2_32_0.default or true);
    clap_2_32_0.strsim =
      (f.clap_2_32_0.strsim or false) ||
      (f.clap_2_32_0.suggestions or false) ||
      (clap_2_32_0.suggestions or false);
    clap_2_32_0.suggestions =
      (f.clap_2_32_0.suggestions or false) ||
      (f.clap_2_32_0.default or false) ||
      (clap_2_32_0.default or false);
    clap_2_32_0.term_size =
      (f.clap_2_32_0.term_size or false) ||
      (f.clap_2_32_0.wrap_help or false) ||
      (clap_2_32_0.wrap_help or false);
    clap_2_32_0.vec_map =
      (f.clap_2_32_0.vec_map or false) ||
      (f.clap_2_32_0.default or false) ||
      (clap_2_32_0.default or false);
    clap_2_32_0.yaml =
      (f.clap_2_32_0.yaml or false) ||
      (f.clap_2_32_0.doc or false) ||
      (clap_2_32_0.doc or false);
    strsim_0_7_0.default = true;
    textwrap_0_10_0.default = true;
    textwrap_0_10_0.term_size =
      (f.textwrap_0_10_0.term_size or false) ||
      (clap_2_32_0.wrap_help or false) ||
      (f.clap_2_32_0.wrap_help or false);
    unicode_width_0_1_5.default = true;
    vec_map_0_8_1.default = true;
  }) [ atty_0_2_11_features bitflags_1_0_4_features strsim_0_7_0_features textwrap_0_10_0_features unicode_width_0_1_5_features vec_map_0_8_1_features ansi_term_0_11_0_features ];
  cloudabi_0_0_3 = { features?(cloudabi_0_0_3_features {}) }: cloudabi_0_0_3_ {
    dependencies = mapFeatures features ([ ]
      ++ (if features.cloudabi_0_0_3.bitflags or false then [ bitflags_1_0_4 ] else []));
    features = mkFeatures (features.cloudabi_0_0_3 or {});
  };
  cloudabi_0_0_3_features = f: updateFeatures f (rec {
    bitflags_1_0_4.default = true;
    cloudabi_0_0_3.bitflags =
      (f.cloudabi_0_0_3.bitflags or false) ||
      (f.cloudabi_0_0_3.default or false) ||
      (cloudabi_0_0_3.default or false);
    cloudabi_0_0_3.default = (f.cloudabi_0_0_3.default or true);
  }) [ bitflags_1_0_4_features ];
  failure_0_1_3 = { features?(failure_0_1_3_features {}) }: failure_0_1_3_ {
    dependencies = mapFeatures features ([ ]
      ++ (if features.failure_0_1_3.backtrace or false then [ backtrace_0_3_9 ] else [])
      ++ (if features.failure_0_1_3.failure_derive or false then [ failure_derive_0_1_3 ] else []));
    features = mkFeatures (features.failure_0_1_3 or {});
  };
  failure_0_1_3_features = f: updateFeatures f (rec {
    backtrace_0_3_9.default = true;
    failure_0_1_3.backtrace =
      (f.failure_0_1_3.backtrace or false) ||
      (f.failure_0_1_3.std or false) ||
      (failure_0_1_3.std or false);
    failure_0_1_3.default = (f.failure_0_1_3.default or true);
    failure_0_1_3.derive =
      (f.failure_0_1_3.derive or false) ||
      (f.failure_0_1_3.default or false) ||
      (failure_0_1_3.default or false);
    failure_0_1_3.failure_derive =
      (f.failure_0_1_3.failure_derive or false) ||
      (f.failure_0_1_3.derive or false) ||
      (failure_0_1_3.derive or false);
    failure_0_1_3.std =
      (f.failure_0_1_3.std or false) ||
      (f.failure_0_1_3.default or false) ||
      (failure_0_1_3.default or false);
    failure_derive_0_1_3.default = true;
  }) [ backtrace_0_3_9_features failure_derive_0_1_3_features ];
  failure_derive_0_1_3 = { features?(failure_derive_0_1_3_features {}) }: failure_derive_0_1_3_ {
    dependencies = mapFeatures features ([ proc_macro2_0_4_20 quote_0_6_9 syn_0_15_18 synstructure_0_10_1 ]);
    features = mkFeatures (features.failure_derive_0_1_3 or {});
  };
  failure_derive_0_1_3_features = f: updateFeatures f (rec {
    failure_derive_0_1_3.default = (f.failure_derive_0_1_3.default or true);
    proc_macro2_0_4_20.default = true;
    quote_0_6_9.default = true;
    syn_0_15_18.default = true;
    synstructure_0_10_1.default = true;
  }) [ proc_macro2_0_4_20_features quote_0_6_9_features syn_0_15_18_features synstructure_0_10_1_features ];
  fuchsia_zircon_0_3_3 = { features?(fuchsia_zircon_0_3_3_features {}) }: fuchsia_zircon_0_3_3_ {
    dependencies = mapFeatures features ([ bitflags_1_0_4 fuchsia_zircon_sys_0_3_3 ]);
  };
  fuchsia_zircon_0_3_3_features = f: updateFeatures f (rec {
    bitflags_1_0_4.default = true;
    fuchsia_zircon_0_3_3.default = (f.fuchsia_zircon_0_3_3.default or true);
    fuchsia_zircon_sys_0_3_3.default = true;
  }) [ bitflags_1_0_4_features fuchsia_zircon_sys_0_3_3_features ];
  fuchsia_zircon_sys_0_3_3 = { features?(fuchsia_zircon_sys_0_3_3_features {}) }: fuchsia_zircon_sys_0_3_3_ {};
  fuchsia_zircon_sys_0_3_3_features = f: updateFeatures f (rec {
    fuchsia_zircon_sys_0_3_3.default = (f.fuchsia_zircon_sys_0_3_3.default or true);
  }) [];
  heck_0_3_0 = { features?(heck_0_3_0_features {}) }: heck_0_3_0_ {
    dependencies = mapFeatures features ([ unicode_segmentation_1_2_1 ]);
  };
  heck_0_3_0_features = f: updateFeatures f (rec {
    heck_0_3_0.default = (f.heck_0_3_0.default or true);
    unicode_segmentation_1_2_1.default = true;
  }) [ unicode_segmentation_1_2_1_features ];
  libc_0_2_43 = { features?(libc_0_2_43_features {}) }: libc_0_2_43_ {
    features = mkFeatures (features.libc_0_2_43 or {});
  };
  libc_0_2_43_features = f: updateFeatures f (rec {
    libc_0_2_43.default = (f.libc_0_2_43.default or true);
    libc_0_2_43.use_std =
      (f.libc_0_2_43.use_std or false) ||
      (f.libc_0_2_43.default or false) ||
      (libc_0_2_43.default or false);
  }) [];
  lock_api_0_1_4 = { features?(lock_api_0_1_4_features {}) }: lock_api_0_1_4_ {
    dependencies = mapFeatures features ([ scopeguard_0_3_3 ]
      ++ (if features.lock_api_0_1_4.owning_ref or false then [ owning_ref_0_3_3 ] else []));
    features = mkFeatures (features.lock_api_0_1_4 or {});
  };
  lock_api_0_1_4_features = f: updateFeatures f (rec {
    lock_api_0_1_4.default = (f.lock_api_0_1_4.default or true);
    owning_ref_0_3_3.default = true;
    scopeguard_0_3_3.default = (f.scopeguard_0_3_3.default or false);
  }) [ owning_ref_0_3_3_features scopeguard_0_3_3_features ];
  nixdoc_1_0_1 = { features?(nixdoc_1_0_1_features {}) }: nixdoc_1_0_1_ {
    dependencies = mapFeatures features ([ failure_0_1_3 rnix_0_5_0 rowan_0_1_2 structopt_0_2_13 xml_rs_0_8_0 ]);
  };
  nixdoc_1_0_1_features = f: updateFeatures f (rec {
    failure_0_1_3.default = true;
    nixdoc_1_0_1.default = (f.nixdoc_1_0_1.default or true);
    rnix_0_5_0.default = true;
    rowan_0_1_2.default = true;
    structopt_0_2_13.default = true;
    xml_rs_0_8_0.default = true;
  }) [ failure_0_1_3_features rnix_0_5_0_features rowan_0_1_2_features structopt_0_2_13_features xml_rs_0_8_0_features ];
  owning_ref_0_3_3 = { features?(owning_ref_0_3_3_features {}) }: owning_ref_0_3_3_ {
    dependencies = mapFeatures features ([ stable_deref_trait_1_1_1 ]);
  };
  owning_ref_0_3_3_features = f: updateFeatures f (rec {
    owning_ref_0_3_3.default = (f.owning_ref_0_3_3.default or true);
    stable_deref_trait_1_1_1.default = true;
  }) [ stable_deref_trait_1_1_1_features ];
  parking_lot_0_6_4 = { features?(parking_lot_0_6_4_features {}) }: parking_lot_0_6_4_ {
    dependencies = mapFeatures features ([ lock_api_0_1_4 parking_lot_core_0_3_1 ]);
    features = mkFeatures (features.parking_lot_0_6_4 or {});
  };
  parking_lot_0_6_4_features = f: updateFeatures f (rec {
    lock_api_0_1_4.default = true;
    lock_api_0_1_4.nightly =
      (f.lock_api_0_1_4.nightly or false) ||
      (parking_lot_0_6_4.nightly or false) ||
      (f.parking_lot_0_6_4.nightly or false);
    lock_api_0_1_4.owning_ref =
      (f.lock_api_0_1_4.owning_ref or false) ||
      (parking_lot_0_6_4.owning_ref or false) ||
      (f.parking_lot_0_6_4.owning_ref or false);
    parking_lot_0_6_4.default = (f.parking_lot_0_6_4.default or true);
    parking_lot_0_6_4.owning_ref =
      (f.parking_lot_0_6_4.owning_ref or false) ||
      (f.parking_lot_0_6_4.default or false) ||
      (parking_lot_0_6_4.default or false);
    parking_lot_core_0_3_1.deadlock_detection =
      (f.parking_lot_core_0_3_1.deadlock_detection or false) ||
      (parking_lot_0_6_4.deadlock_detection or false) ||
      (f.parking_lot_0_6_4.deadlock_detection or false);
    parking_lot_core_0_3_1.default = true;
    parking_lot_core_0_3_1.nightly =
      (f.parking_lot_core_0_3_1.nightly or false) ||
      (parking_lot_0_6_4.nightly or false) ||
      (f.parking_lot_0_6_4.nightly or false);
  }) [ lock_api_0_1_4_features parking_lot_core_0_3_1_features ];
  parking_lot_core_0_3_1 = { features?(parking_lot_core_0_3_1_features {}) }: parking_lot_core_0_3_1_ {
    dependencies = mapFeatures features ([ rand_0_5_5 smallvec_0_6_5 ])
      ++ (if (kernel == "linux" || kernel == "darwin") then mapFeatures features ([ libc_0_2_43 ]) else [])
      ++ (if kernel == "windows" then mapFeatures features ([ winapi_0_3_6 ]) else []);
    buildDependencies = mapFeatures features ([ rustc_version_0_2_3 ]);
    features = mkFeatures (features.parking_lot_core_0_3_1 or {});
  };
  parking_lot_core_0_3_1_features = f: updateFeatures f (rec {
    libc_0_2_43.default = true;
    parking_lot_core_0_3_1."thread-id" =
      (f.parking_lot_core_0_3_1."thread-id" or false) ||
      (f.parking_lot_core_0_3_1.deadlock_detection or false) ||
      (parking_lot_core_0_3_1.deadlock_detection or false);
    parking_lot_core_0_3_1.backtrace =
      (f.parking_lot_core_0_3_1.backtrace or false) ||
      (f.parking_lot_core_0_3_1.deadlock_detection or false) ||
      (parking_lot_core_0_3_1.deadlock_detection or false);
    parking_lot_core_0_3_1.default = (f.parking_lot_core_0_3_1.default or true);
    parking_lot_core_0_3_1.petgraph =
      (f.parking_lot_core_0_3_1.petgraph or false) ||
      (f.parking_lot_core_0_3_1.deadlock_detection or false) ||
      (parking_lot_core_0_3_1.deadlock_detection or false);
    rand_0_5_5.default = true;
    rustc_version_0_2_3.default = true;
    smallvec_0_6_5.default = true;
    winapi_0_3_6.default = true;
    winapi_0_3_6.errhandlingapi = true;
    winapi_0_3_6.handleapi = true;
    winapi_0_3_6.minwindef = true;
    winapi_0_3_6.ntstatus = true;
    winapi_0_3_6.winbase = true;
    winapi_0_3_6.winerror = true;
    winapi_0_3_6.winnt = true;
  }) [ rand_0_5_5_features smallvec_0_6_5_features rustc_version_0_2_3_features libc_0_2_43_features winapi_0_3_6_features ];
  proc_macro2_0_4_20 = { features?(proc_macro2_0_4_20_features {}) }: proc_macro2_0_4_20_ {
    dependencies = mapFeatures features ([ unicode_xid_0_1_0 ]);
    features = mkFeatures (features.proc_macro2_0_4_20 or {});
  };
  proc_macro2_0_4_20_features = f: updateFeatures f (rec {
    proc_macro2_0_4_20."proc-macro" =
      (f.proc_macro2_0_4_20."proc-macro" or false) ||
      (f.proc_macro2_0_4_20.default or false) ||
      (proc_macro2_0_4_20.default or false) ||
      (f.proc_macro2_0_4_20.nightly or false) ||
      (proc_macro2_0_4_20.nightly or false);
    proc_macro2_0_4_20.default = (f.proc_macro2_0_4_20.default or true);
    unicode_xid_0_1_0.default = true;
  }) [ unicode_xid_0_1_0_features ];
  quote_0_6_9 = { features?(quote_0_6_9_features {}) }: quote_0_6_9_ {
    dependencies = mapFeatures features ([ proc_macro2_0_4_20 ]);
    features = mkFeatures (features.quote_0_6_9 or {});
  };
  quote_0_6_9_features = f: updateFeatures f (rec {
    proc_macro2_0_4_20."proc-macro" =
      (f.proc_macro2_0_4_20."proc-macro" or false) ||
      (quote_0_6_9."proc-macro" or false) ||
      (f.quote_0_6_9."proc-macro" or false);
    proc_macro2_0_4_20.default = (f.proc_macro2_0_4_20.default or false);
    quote_0_6_9."proc-macro" =
      (f.quote_0_6_9."proc-macro" or false) ||
      (f.quote_0_6_9.default or false) ||
      (quote_0_6_9.default or false);
    quote_0_6_9.default = (f.quote_0_6_9.default or true);
  }) [ proc_macro2_0_4_20_features ];
  rand_0_5_5 = { features?(rand_0_5_5_features {}) }: rand_0_5_5_ {
    dependencies = mapFeatures features ([ rand_core_0_2_2 ])
      ++ (if kernel == "cloudabi" then mapFeatures features ([ ]
      ++ (if features.rand_0_5_5.cloudabi or false then [ cloudabi_0_0_3 ] else [])) else [])
      ++ (if kernel == "fuchsia" then mapFeatures features ([ ]
      ++ (if features.rand_0_5_5."fuchsia-zircon" or false then [ fuchsia_zircon_0_3_3 ] else [])) else [])
      ++ (if (kernel == "linux" || kernel == "darwin") then mapFeatures features ([ ]
      ++ (if features.rand_0_5_5.libc or false then [ libc_0_2_43 ] else [])) else [])
      ++ (if kernel == "windows" then mapFeatures features ([ ]
      ++ (if features.rand_0_5_5.winapi or false then [ winapi_0_3_6 ] else [])) else [])
      ++ (if kernel == "wasm32-unknown-unknown" then mapFeatures features ([]) else []);
    features = mkFeatures (features.rand_0_5_5 or {});
  };
  rand_0_5_5_features = f: updateFeatures f (rec {
    cloudabi_0_0_3.default = true;
    fuchsia_zircon_0_3_3.default = true;
    libc_0_2_43.default = true;
    rand_0_5_5."fuchsia-zircon" =
      (f.rand_0_5_5."fuchsia-zircon" or false) ||
      (f.rand_0_5_5.std or false) ||
      (rand_0_5_5.std or false);
    rand_0_5_5."i128_support" =
      (f.rand_0_5_5."i128_support" or false) ||
      (f.rand_0_5_5.nightly or false) ||
      (rand_0_5_5.nightly or false);
    rand_0_5_5.alloc =
      (f.rand_0_5_5.alloc or false) ||
      (f.rand_0_5_5.std or false) ||
      (rand_0_5_5.std or false);
    rand_0_5_5.cloudabi =
      (f.rand_0_5_5.cloudabi or false) ||
      (f.rand_0_5_5.std or false) ||
      (rand_0_5_5.std or false);
    rand_0_5_5.default = (f.rand_0_5_5.default or true);
    rand_0_5_5.libc =
      (f.rand_0_5_5.libc or false) ||
      (f.rand_0_5_5.std or false) ||
      (rand_0_5_5.std or false);
    rand_0_5_5.serde =
      (f.rand_0_5_5.serde or false) ||
      (f.rand_0_5_5."serde1" or false) ||
      (rand_0_5_5."serde1" or false);
    rand_0_5_5.serde_derive =
      (f.rand_0_5_5.serde_derive or false) ||
      (f.rand_0_5_5."serde1" or false) ||
      (rand_0_5_5."serde1" or false);
    rand_0_5_5.std =
      (f.rand_0_5_5.std or false) ||
      (f.rand_0_5_5.default or false) ||
      (rand_0_5_5.default or false);
    rand_0_5_5.winapi =
      (f.rand_0_5_5.winapi or false) ||
      (f.rand_0_5_5.std or false) ||
      (rand_0_5_5.std or false);
    rand_core_0_2_2."serde1" =
      (f.rand_core_0_2_2."serde1" or false) ||
      (rand_0_5_5."serde1" or false) ||
      (f.rand_0_5_5."serde1" or false);
    rand_core_0_2_2.alloc =
      (f.rand_core_0_2_2.alloc or false) ||
      (rand_0_5_5.alloc or false) ||
      (f.rand_0_5_5.alloc or false);
    rand_core_0_2_2.default = (f.rand_core_0_2_2.default or false);
    rand_core_0_2_2.std =
      (f.rand_core_0_2_2.std or false) ||
      (rand_0_5_5.std or false) ||
      (f.rand_0_5_5.std or false);
    winapi_0_3_6.default = true;
    winapi_0_3_6.minwindef = true;
    winapi_0_3_6.ntsecapi = true;
    winapi_0_3_6.profileapi = true;
    winapi_0_3_6.winnt = true;
  }) [ rand_core_0_2_2_features cloudabi_0_0_3_features fuchsia_zircon_0_3_3_features libc_0_2_43_features winapi_0_3_6_features ];
  rand_core_0_2_2 = { features?(rand_core_0_2_2_features {}) }: rand_core_0_2_2_ {
    dependencies = mapFeatures features ([ rand_core_0_3_0 ]);
    features = mkFeatures (features.rand_core_0_2_2 or {});
  };
  rand_core_0_2_2_features = f: updateFeatures f (rec {
    rand_core_0_2_2.default = (f.rand_core_0_2_2.default or true);
    rand_core_0_3_0."serde1" =
      (f.rand_core_0_3_0."serde1" or false) ||
      (rand_core_0_2_2."serde1" or false) ||
      (f.rand_core_0_2_2."serde1" or false);
    rand_core_0_3_0.alloc =
      (f.rand_core_0_3_0.alloc or false) ||
      (rand_core_0_2_2.alloc or false) ||
      (f.rand_core_0_2_2.alloc or false);
    rand_core_0_3_0.default = (f.rand_core_0_3_0.default or false);
    rand_core_0_3_0.std =
      (f.rand_core_0_3_0.std or false) ||
      (rand_core_0_2_2.std or false) ||
      (f.rand_core_0_2_2.std or false);
  }) [ rand_core_0_3_0_features ];
  rand_core_0_3_0 = { features?(rand_core_0_3_0_features {}) }: rand_core_0_3_0_ {
    dependencies = mapFeatures features ([]);
    features = mkFeatures (features.rand_core_0_3_0 or {});
  };
  rand_core_0_3_0_features = f: updateFeatures f (rec {
    rand_core_0_3_0.alloc =
      (f.rand_core_0_3_0.alloc or false) ||
      (f.rand_core_0_3_0.std or false) ||
      (rand_core_0_3_0.std or false);
    rand_core_0_3_0.default = (f.rand_core_0_3_0.default or true);
    rand_core_0_3_0.serde =
      (f.rand_core_0_3_0.serde or false) ||
      (f.rand_core_0_3_0."serde1" or false) ||
      (rand_core_0_3_0."serde1" or false);
    rand_core_0_3_0.serde_derive =
      (f.rand_core_0_3_0.serde_derive or false) ||
      (f.rand_core_0_3_0."serde1" or false) ||
      (rand_core_0_3_0."serde1" or false);
    rand_core_0_3_0.std =
      (f.rand_core_0_3_0.std or false) ||
      (f.rand_core_0_3_0.default or false) ||
      (rand_core_0_3_0.default or false);
  }) [];
  redox_syscall_0_1_40 = { features?(redox_syscall_0_1_40_features {}) }: redox_syscall_0_1_40_ {};
  redox_syscall_0_1_40_features = f: updateFeatures f (rec {
    redox_syscall_0_1_40.default = (f.redox_syscall_0_1_40.default or true);
  }) [];
  redox_termios_0_1_1 = { features?(redox_termios_0_1_1_features {}) }: redox_termios_0_1_1_ {
    dependencies = mapFeatures features ([ redox_syscall_0_1_40 ]);
  };
  redox_termios_0_1_1_features = f: updateFeatures f (rec {
    redox_syscall_0_1_40.default = true;
    redox_termios_0_1_1.default = (f.redox_termios_0_1_1.default or true);
  }) [ redox_syscall_0_1_40_features ];
  rnix_0_5_0 = { features?(rnix_0_5_0_features {}) }: rnix_0_5_0_ {
    dependencies = mapFeatures features ([ failure_0_1_3 rowan_0_1_2 ]);
  };
  rnix_0_5_0_features = f: updateFeatures f (rec {
    failure_0_1_3.default = true;
    rnix_0_5_0.default = (f.rnix_0_5_0.default or true);
    rowan_0_1_2.default = true;
  }) [ failure_0_1_3_features rowan_0_1_2_features ];
  rowan_0_1_2 = { features?(rowan_0_1_2_features {}) }: rowan_0_1_2_ {
    dependencies = mapFeatures features ([ parking_lot_0_6_4 smol_str_0_1_7 text_unit_0_1_5 ]);
  };
  rowan_0_1_2_features = f: updateFeatures f (rec {
    parking_lot_0_6_4.default = true;
    rowan_0_1_2.default = (f.rowan_0_1_2.default or true);
    smol_str_0_1_7.default = true;
    text_unit_0_1_5.default = true;
  }) [ parking_lot_0_6_4_features smol_str_0_1_7_features text_unit_0_1_5_features ];
  rustc_demangle_0_1_9 = { features?(rustc_demangle_0_1_9_features {}) }: rustc_demangle_0_1_9_ {};
  rustc_demangle_0_1_9_features = f: updateFeatures f (rec {
    rustc_demangle_0_1_9.default = (f.rustc_demangle_0_1_9.default or true);
  }) [];
  rustc_version_0_2_3 = { features?(rustc_version_0_2_3_features {}) }: rustc_version_0_2_3_ {
    dependencies = mapFeatures features ([ semver_0_9_0 ]);
  };
  rustc_version_0_2_3_features = f: updateFeatures f (rec {
    rustc_version_0_2_3.default = (f.rustc_version_0_2_3.default or true);
    semver_0_9_0.default = true;
  }) [ semver_0_9_0_features ];
  scopeguard_0_3_3 = { features?(scopeguard_0_3_3_features {}) }: scopeguard_0_3_3_ {
    features = mkFeatures (features.scopeguard_0_3_3 or {});
  };
  scopeguard_0_3_3_features = f: updateFeatures f (rec {
    scopeguard_0_3_3.default = (f.scopeguard_0_3_3.default or true);
    scopeguard_0_3_3.use_std =
      (f.scopeguard_0_3_3.use_std or false) ||
      (f.scopeguard_0_3_3.default or false) ||
      (scopeguard_0_3_3.default or false);
  }) [];
  semver_0_9_0 = { features?(semver_0_9_0_features {}) }: semver_0_9_0_ {
    dependencies = mapFeatures features ([ semver_parser_0_7_0 ]);
    features = mkFeatures (features.semver_0_9_0 or {});
  };
  semver_0_9_0_features = f: updateFeatures f (rec {
    semver_0_9_0.default = (f.semver_0_9_0.default or true);
    semver_0_9_0.serde =
      (f.semver_0_9_0.serde or false) ||
      (f.semver_0_9_0.ci or false) ||
      (semver_0_9_0.ci or false);
    semver_parser_0_7_0.default = true;
  }) [ semver_parser_0_7_0_features ];
  semver_parser_0_7_0 = { features?(semver_parser_0_7_0_features {}) }: semver_parser_0_7_0_ {};
  semver_parser_0_7_0_features = f: updateFeatures f (rec {
    semver_parser_0_7_0.default = (f.semver_parser_0_7_0.default or true);
  }) [];
  smallvec_0_6_5 = { features?(smallvec_0_6_5_features {}) }: smallvec_0_6_5_ {
    dependencies = mapFeatures features ([ unreachable_1_0_0 ]);
    features = mkFeatures (features.smallvec_0_6_5 or {});
  };
  smallvec_0_6_5_features = f: updateFeatures f (rec {
    smallvec_0_6_5.default = (f.smallvec_0_6_5.default or true);
    smallvec_0_6_5.std =
      (f.smallvec_0_6_5.std or false) ||
      (f.smallvec_0_6_5.default or false) ||
      (smallvec_0_6_5.default or false);
    unreachable_1_0_0.default = true;
  }) [ unreachable_1_0_0_features ];
  smol_str_0_1_7 = { features?(smol_str_0_1_7_features {}) }: smol_str_0_1_7_ {
    dependencies = mapFeatures features ([]);
  };
  smol_str_0_1_7_features = f: updateFeatures f (rec {
    smol_str_0_1_7.default = (f.smol_str_0_1_7.default or true);
  }) [];
  stable_deref_trait_1_1_1 = { features?(stable_deref_trait_1_1_1_features {}) }: stable_deref_trait_1_1_1_ {
    features = mkFeatures (features.stable_deref_trait_1_1_1 or {});
  };
  stable_deref_trait_1_1_1_features = f: updateFeatures f (rec {
    stable_deref_trait_1_1_1.default = (f.stable_deref_trait_1_1_1.default or true);
    stable_deref_trait_1_1_1.std =
      (f.stable_deref_trait_1_1_1.std or false) ||
      (f.stable_deref_trait_1_1_1.default or false) ||
      (stable_deref_trait_1_1_1.default or false);
  }) [];
  strsim_0_7_0 = { features?(strsim_0_7_0_features {}) }: strsim_0_7_0_ {};
  strsim_0_7_0_features = f: updateFeatures f (rec {
    strsim_0_7_0.default = (f.strsim_0_7_0.default or true);
  }) [];
  structopt_0_2_13 = { features?(structopt_0_2_13_features {}) }: structopt_0_2_13_ {
    dependencies = mapFeatures features ([ clap_2_32_0 structopt_derive_0_2_13 ]);
    features = mkFeatures (features.structopt_0_2_13 or {});
  };
  structopt_0_2_13_features = f: updateFeatures f (rec {
    clap_2_32_0.color =
      (f.clap_2_32_0.color or false) ||
      (structopt_0_2_13.color or false) ||
      (f.structopt_0_2_13.color or false);
    clap_2_32_0.debug =
      (f.clap_2_32_0.debug or false) ||
      (structopt_0_2_13.debug or false) ||
      (f.structopt_0_2_13.debug or false);
    clap_2_32_0.default =
      (f.clap_2_32_0.default or false) ||
      (structopt_0_2_13.default or false) ||
      (f.structopt_0_2_13.default or false) ||
      false;
    clap_2_32_0.doc =
      (f.clap_2_32_0.doc or false) ||
      (structopt_0_2_13.doc or false) ||
      (f.structopt_0_2_13.doc or false);
    clap_2_32_0.lints =
      (f.clap_2_32_0.lints or false) ||
      (structopt_0_2_13.lints or false) ||
      (f.structopt_0_2_13.lints or false);
    clap_2_32_0.no_cargo =
      (f.clap_2_32_0.no_cargo or false) ||
      (structopt_0_2_13.no_cargo or false) ||
      (f.structopt_0_2_13.no_cargo or false);
    clap_2_32_0.suggestions =
      (f.clap_2_32_0.suggestions or false) ||
      (structopt_0_2_13.suggestions or false) ||
      (f.structopt_0_2_13.suggestions or false);
    clap_2_32_0.wrap_help =
      (f.clap_2_32_0.wrap_help or false) ||
      (structopt_0_2_13.wrap_help or false) ||
      (f.structopt_0_2_13.wrap_help or false);
    clap_2_32_0.yaml =
      (f.clap_2_32_0.yaml or false) ||
      (structopt_0_2_13.yaml or false) ||
      (f.structopt_0_2_13.yaml or false);
    structopt_0_2_13.default = (f.structopt_0_2_13.default or true);
    structopt_derive_0_2_13.default = true;
    structopt_derive_0_2_13.nightly =
      (f.structopt_derive_0_2_13.nightly or false) ||
      (structopt_0_2_13.nightly or false) ||
      (f.structopt_0_2_13.nightly or false);
  }) [ clap_2_32_0_features structopt_derive_0_2_13_features ];
  structopt_derive_0_2_13 = { features?(structopt_derive_0_2_13_features {}) }: structopt_derive_0_2_13_ {
    dependencies = mapFeatures features ([ heck_0_3_0 proc_macro2_0_4_20 quote_0_6_9 syn_0_15_18 ]);
    features = mkFeatures (features.structopt_derive_0_2_13 or {});
  };
  structopt_derive_0_2_13_features = f: updateFeatures f (rec {
    heck_0_3_0.default = true;
    proc_macro2_0_4_20.default = true;
    proc_macro2_0_4_20.nightly =
      (f.proc_macro2_0_4_20.nightly or false) ||
      (structopt_derive_0_2_13.nightly or false) ||
      (f.structopt_derive_0_2_13.nightly or false);
    quote_0_6_9.default = true;
    structopt_derive_0_2_13.default = (f.structopt_derive_0_2_13.default or true);
    syn_0_15_18.default = true;
  }) [ heck_0_3_0_features proc_macro2_0_4_20_features quote_0_6_9_features syn_0_15_18_features ];
  syn_0_15_18 = { features?(syn_0_15_18_features {}) }: syn_0_15_18_ {
    dependencies = mapFeatures features ([ proc_macro2_0_4_20 unicode_xid_0_1_0 ]
      ++ (if features.syn_0_15_18.quote or false then [ quote_0_6_9 ] else []));
    features = mkFeatures (features.syn_0_15_18 or {});
  };
  syn_0_15_18_features = f: updateFeatures f (rec {
    proc_macro2_0_4_20."proc-macro" =
      (f.proc_macro2_0_4_20."proc-macro" or false) ||
      (syn_0_15_18."proc-macro" or false) ||
      (f.syn_0_15_18."proc-macro" or false);
    proc_macro2_0_4_20.default = (f.proc_macro2_0_4_20.default or false);
    quote_0_6_9."proc-macro" =
      (f.quote_0_6_9."proc-macro" or false) ||
      (syn_0_15_18."proc-macro" or false) ||
      (f.syn_0_15_18."proc-macro" or false);
    quote_0_6_9.default = (f.quote_0_6_9.default or false);
    syn_0_15_18."clone-impls" =
      (f.syn_0_15_18."clone-impls" or false) ||
      (f.syn_0_15_18.default or false) ||
      (syn_0_15_18.default or false);
    syn_0_15_18."proc-macro" =
      (f.syn_0_15_18."proc-macro" or false) ||
      (f.syn_0_15_18.default or false) ||
      (syn_0_15_18.default or false);
    syn_0_15_18.default = (f.syn_0_15_18.default or true);
    syn_0_15_18.derive =
      (f.syn_0_15_18.derive or false) ||
      (f.syn_0_15_18.default or false) ||
      (syn_0_15_18.default or false);
    syn_0_15_18.parsing =
      (f.syn_0_15_18.parsing or false) ||
      (f.syn_0_15_18.default or false) ||
      (syn_0_15_18.default or false);
    syn_0_15_18.printing =
      (f.syn_0_15_18.printing or false) ||
      (f.syn_0_15_18.default or false) ||
      (syn_0_15_18.default or false);
    syn_0_15_18.quote =
      (f.syn_0_15_18.quote or false) ||
      (f.syn_0_15_18.printing or false) ||
      (syn_0_15_18.printing or false);
    unicode_xid_0_1_0.default = true;
  }) [ proc_macro2_0_4_20_features quote_0_6_9_features unicode_xid_0_1_0_features ];
  synstructure_0_10_1 = { features?(synstructure_0_10_1_features {}) }: synstructure_0_10_1_ {
    dependencies = mapFeatures features ([ proc_macro2_0_4_20 quote_0_6_9 syn_0_15_18 unicode_xid_0_1_0 ]);
    features = mkFeatures (features.synstructure_0_10_1 or {});
  };
  synstructure_0_10_1_features = f: updateFeatures f (rec {
    proc_macro2_0_4_20.default = true;
    quote_0_6_9.default = true;
    syn_0_15_18."extra-traits" = true;
    syn_0_15_18.default = true;
    syn_0_15_18.visit = true;
    synstructure_0_10_1.default = (f.synstructure_0_10_1.default or true);
    unicode_xid_0_1_0.default = true;
  }) [ proc_macro2_0_4_20_features quote_0_6_9_features syn_0_15_18_features unicode_xid_0_1_0_features ];
  termion_1_5_1 = { features?(termion_1_5_1_features {}) }: termion_1_5_1_ {
    dependencies = (if !(kernel == "redox") then mapFeatures features ([ libc_0_2_43 ]) else [])
      ++ (if kernel == "redox" then mapFeatures features ([ redox_syscall_0_1_40 redox_termios_0_1_1 ]) else []);
  };
  termion_1_5_1_features = f: updateFeatures f (rec {
    libc_0_2_43.default = true;
    redox_syscall_0_1_40.default = true;
    redox_termios_0_1_1.default = true;
    termion_1_5_1.default = (f.termion_1_5_1.default or true);
  }) [ libc_0_2_43_features redox_syscall_0_1_40_features redox_termios_0_1_1_features ];
  text_unit_0_1_5 = { features?(text_unit_0_1_5_features {}) }: text_unit_0_1_5_ {
    dependencies = mapFeatures features ([]);
  };
  text_unit_0_1_5_features = f: updateFeatures f (rec {
    text_unit_0_1_5.default = (f.text_unit_0_1_5.default or true);
  }) [];
  textwrap_0_10_0 = { features?(textwrap_0_10_0_features {}) }: textwrap_0_10_0_ {
    dependencies = mapFeatures features ([ unicode_width_0_1_5 ]);
  };
  textwrap_0_10_0_features = f: updateFeatures f (rec {
    textwrap_0_10_0.default = (f.textwrap_0_10_0.default or true);
    unicode_width_0_1_5.default = true;
  }) [ unicode_width_0_1_5_features ];
  unicode_segmentation_1_2_1 = { features?(unicode_segmentation_1_2_1_features {}) }: unicode_segmentation_1_2_1_ {
    features = mkFeatures (features.unicode_segmentation_1_2_1 or {});
  };
  unicode_segmentation_1_2_1_features = f: updateFeatures f (rec {
    unicode_segmentation_1_2_1.default = (f.unicode_segmentation_1_2_1.default or true);
  }) [];
  unicode_width_0_1_5 = { features?(unicode_width_0_1_5_features {}) }: unicode_width_0_1_5_ {
    features = mkFeatures (features.unicode_width_0_1_5 or {});
  };
  unicode_width_0_1_5_features = f: updateFeatures f (rec {
    unicode_width_0_1_5.default = (f.unicode_width_0_1_5.default or true);
  }) [];
  unicode_xid_0_1_0 = { features?(unicode_xid_0_1_0_features {}) }: unicode_xid_0_1_0_ {
    features = mkFeatures (features.unicode_xid_0_1_0 or {});
  };
  unicode_xid_0_1_0_features = f: updateFeatures f (rec {
    unicode_xid_0_1_0.default = (f.unicode_xid_0_1_0.default or true);
  }) [];
  unreachable_1_0_0 = { features?(unreachable_1_0_0_features {}) }: unreachable_1_0_0_ {
    dependencies = mapFeatures features ([ void_1_0_2 ]);
  };
  unreachable_1_0_0_features = f: updateFeatures f (rec {
    unreachable_1_0_0.default = (f.unreachable_1_0_0.default or true);
    void_1_0_2.default = (f.void_1_0_2.default or false);
  }) [ void_1_0_2_features ];
  vec_map_0_8_1 = { features?(vec_map_0_8_1_features {}) }: vec_map_0_8_1_ {
    dependencies = mapFeatures features ([]);
    features = mkFeatures (features.vec_map_0_8_1 or {});
  };
  vec_map_0_8_1_features = f: updateFeatures f (rec {
    vec_map_0_8_1.default = (f.vec_map_0_8_1.default or true);
    vec_map_0_8_1.serde =
      (f.vec_map_0_8_1.serde or false) ||
      (f.vec_map_0_8_1.eders or false) ||
      (vec_map_0_8_1.eders or false);
  }) [];
  void_1_0_2 = { features?(void_1_0_2_features {}) }: void_1_0_2_ {
    features = mkFeatures (features.void_1_0_2 or {});
  };
  void_1_0_2_features = f: updateFeatures f (rec {
    void_1_0_2.default = (f.void_1_0_2.default or true);
    void_1_0_2.std =
      (f.void_1_0_2.std or false) ||
      (f.void_1_0_2.default or false) ||
      (void_1_0_2.default or false);
  }) [];
  winapi_0_3_6 = { features?(winapi_0_3_6_features {}) }: winapi_0_3_6_ {
    dependencies = (if kernel == "i686-pc-windows-gnu" then mapFeatures features ([ winapi_i686_pc_windows_gnu_0_4_0 ]) else [])
      ++ (if kernel == "x86_64-pc-windows-gnu" then mapFeatures features ([ winapi_x86_64_pc_windows_gnu_0_4_0 ]) else []);
    features = mkFeatures (features.winapi_0_3_6 or {});
  };
  winapi_0_3_6_features = f: updateFeatures f (rec {
    winapi_0_3_6.default = (f.winapi_0_3_6.default or true);
    winapi_i686_pc_windows_gnu_0_4_0.default = true;
    winapi_x86_64_pc_windows_gnu_0_4_0.default = true;
  }) [ winapi_i686_pc_windows_gnu_0_4_0_features winapi_x86_64_pc_windows_gnu_0_4_0_features ];
  winapi_i686_pc_windows_gnu_0_4_0 = { features?(winapi_i686_pc_windows_gnu_0_4_0_features {}) }: winapi_i686_pc_windows_gnu_0_4_0_ {};
  winapi_i686_pc_windows_gnu_0_4_0_features = f: updateFeatures f (rec {
    winapi_i686_pc_windows_gnu_0_4_0.default = (f.winapi_i686_pc_windows_gnu_0_4_0.default or true);
  }) [];
  winapi_x86_64_pc_windows_gnu_0_4_0 = { features?(winapi_x86_64_pc_windows_gnu_0_4_0_features {}) }: winapi_x86_64_pc_windows_gnu_0_4_0_ {};
  winapi_x86_64_pc_windows_gnu_0_4_0_features = f: updateFeatures f (rec {
    winapi_x86_64_pc_windows_gnu_0_4_0.default = (f.winapi_x86_64_pc_windows_gnu_0_4_0.default or true);
  }) [];
  xml_rs_0_8_0 = { features?(xml_rs_0_8_0_features {}) }: xml_rs_0_8_0_ {};
  xml_rs_0_8_0_features = f: updateFeatures f (rec {
    xml_rs_0_8_0.default = (f.xml_rs_0_8_0.default or true);
  }) [];
}
